package org.example.ios

import io.outfoxx.swiftpoet.DeclaredTypeName
import io.outfoxx.swiftpoet.ExtensionSpec
import io.outfoxx.swiftpoet.FileSpec
import io.outfoxx.swiftpoet.FunctionSpec
import io.outfoxx.swiftpoet.Modifier
import io.outfoxx.swiftpoet.PropertySpec
import org.example.android.ColorTreeElement
import org.example.android.VariableMode
import java.io.File

fun generateSwiftPalletFileFlat(
    outputFile: File,
    modes: Map<String, VariableMode>,
) {
    val palletName = outputFile.nameWithoutExtension

    val extensionBuilder = ExtensionSpec.builder(DeclaredTypeName("SwiftUI", "View"))

    if (modes.size == 1) {
        val colors = modes.values.first().colors
        addColorElementFlat(extensionBuilder, listOf(), colors)
    } else {
        val light = modes.values.first { it.name == "Light" }.colors
        val dark = modes.values.first { it.name == "Dark" }.colors
        addColorElementFlat(extensionBuilder, listOf(), light, dark)
    }

    val fileSpec = FileSpec.builder(palletName)
        .addComment("""
            DO NOT EDIT.
            swift-format-ignore-file
            swiftlint:disable line_length
            Autogenerated code from https://github.com/LionZXY/FlipperPalletGenerator
        """.trimIndent())
        .addExtension(extensionBuilder.build())
        .addExtension(generateColorExtension())
        .addImport("SwiftUI")
        .indent("    ")
        .build()

    val content = "$fileSpec// swiftlint:enable line_length\n"
    outputFile.writeText(content)
}

private fun addColorElementFlat(
    builder: ExtensionSpec.Builder,
    path: List<String>,
    element: ColorTreeElement,
    darkElement: ColorTreeElement? = null
) {
    when (element) {
        is ColorTreeElement.Color -> {
            // Формируем camelCase: первая часть с маленькой, остальные с большой буквы
            val propName = path.mapIndexed { index, part ->
                if (index == 0) part.replaceFirstChar { it.lowercase() }
                else part.replaceFirstChar { it.uppercase() }
            }.joinToString("")

            val initializer = if (darkElement != null && darkElement is ColorTreeElement.Color) {
                "Color(any: Color(red: ${element.red}, green: ${element.green}, blue: ${element.blue}, opacity: ${element.alpha}), " +
                        "dark: Color(red: ${darkElement.red}, green: ${darkElement.green}, blue: ${darkElement.blue}, opacity: ${darkElement.alpha}))"
            } else {
                "Color(red: ${element.red}, green: ${element.green}, blue: ${element.blue}, opacity: ${element.alpha})"
            }

            builder.addProperty(
                PropertySpec.builder(propName, DeclaredTypeName("SwiftUI", "Color"))
                    .addModifiers(Modifier.STATIC)
                    .getter(FunctionSpec.getterBuilder().addStatement(initializer).build())
                    .build()
            )
        }
        is ColorTreeElement.Collection -> {
            element.map.forEach { (name, child) ->
                addColorElementFlat(
                    builder,
                    path + name,
                    child,
                    darkElement?.let { (it as? ColorTreeElement.Collection)?.map?.get(name) }
                )
            }
        }
    }
}

private fun generateColorExtension(): ExtensionSpec {
    return ExtensionSpec
        .builder(DeclaredTypeName("SwiftUI", "Color"))
        .addFunction(
            FunctionSpec
                .constructorBuilder()
                .addParameter("any", type = DeclaredTypeName("SwiftUI", "Color"))
                .addParameter("dark", type = DeclaredTypeName("SwiftUI", "Color"))
                .addCode(
                    """
                    #if canImport(UIKit)
                    self.init(UIColor { traitCollection in
                        traitCollection.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(any)
                    })
                    #elseif canImport(AppKit)
                    self.init(NSColor { appearance in
                        let isDark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
                        return isDark ? NSColor(dark) : NSColor(any)
                    })
                    #else
                    self = any
                    #endif
                    """.trimIndent()
                )
                .build()
        )
        .build()
}

private val ColorTreeElement.Color.red: Float get() = color.red / 255f
private val ColorTreeElement.Color.green: Float get() = color.green / 255f
private val ColorTreeElement.Color.blue: Float get() = color.blue / 255f
private val ColorTreeElement.Color.alpha: Float get() = color.alpha / 255f
